# Generated by Django 4.1.5 on 2023-02-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_cover_recipe_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
